### ISSUE TITLE
Stock Update Error: Data too long for column 'pictureUrl' at row 1

### ISSUE THREAD

**Issue by mushanga** [eguller/twitstreet#212]
13:00:48,365 ERROR Stock Update Task StockMgrImpl:444 - DB: Query failed - com.mysql.jdbc.JDBC4PreparedStatement@1e4c6c3: update stock set total = 15747, pictureUrl = 'http://a0.twimg.com/profile_images/1647424795/__CC_BD_E2_96_B4_CC_8A_CC_B2_CC_BD_E2_96_B4_CC_8A_CC_B2_CC_BD_CC_BD_E2_96_B4_CC_8A_CC_B2_CC_BD__CC_BD_20Goga_20Dhaliwal_20__CC_BD_E2_96_B4_CC_8A_CC_B2_CC_BD_E2_96_B4_CC_8A_CC_B2_CC_BD_CC_BD_E2_96_B4_CC_8A_CC_B2_CC_BD__CC_BD_normal.jpg', lastUpdate = now(), name = 'jazzyb',longName = 'Jazzy B', verified = 1,language = 'en',description = 'The Crown Prince of Bhangra! To enter the world of JzB is to discover a universe where the exceptional is the rule. All hail the King!', createdAt='2010-11-12', location = 'Birmingham, United Kingdom'  where id = 214924885
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'pictureUrl' at row 1
       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3607)
       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
       at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
       at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
       at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
       at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
       at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
       at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
       at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
       at com.twitstreet.market.StockMgrImpl.updateTwitterData(StockMgrImpl.java:423)
       at com.twitstreet.market.StockMgrImpl.updateStockListData(StockMgrImpl.java:289)
       at com.twitstreet.task.StockUpdateTask.updateStocks(StockUpdateTask.java:161)
       at com.twitstreet.task.StockUpdateTask.run(StockUpdateTask.java:78)
       at java.lang.Thread.run(Thread.java:636)

**Comment by eguller** [comment]
its length is 281 I have increased length of picture url is to 1023
